apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # deployment name
  name: bp-deployment
  labels:
    app: bp
spec:
  # modify replicas according to your case
  replicas: 3
  # updating deployment strategy
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 33%
  # pod template
  template:
    metadata:
      labels:
        app: bp
    spec:
      # pod contains 1 container
      containers:
      - name: bp
        image: ca1acr.azurecr.io/ca-back-end-thin:latest 
        # container opens port 8080
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP            
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: bp-service
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: LoadBalancer
  ports:
    # Accept traffic sent to port 8080
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: bp
